function out = generateFeatures(in,Bands)
    out = [
        Normalizza(AvgFeatures(in,Bands))...
        ,Normalizza(MinFeatures(in,Bands))...
        ,Normalizza(MaxFeatures(in,Bands))...
        ,Normalizza(StdFeatures(in,Bands))...
        ,Normalizza(ModeFeatures(in,Bands))...
        ,Normalizza(VarFeatures(in,Bands))...
        ];
end